# Generated by Django 4.1.4 on 2022-12-25 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['title'], 'verbose_name': 'задачу', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task_manager.category'),
        ),
    ]
