# Generated by Django 4.1.4 on 2023-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_category_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descript',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
